Vagrant.configure("2") do |config|
  # Используем образ Ubuntu 18.04
  config.vm.box = "ubuntu/bionic64"

  # Настройка сети (опционально)
  config.vm.network "private_network", ip: "192.168.33.10"

  # Копируем пустой файл на виртуальную машину
  config.vm.provision "file", source: "./empty_file.txt", destination: "/home/vagrant/empty_file.txt"

  # Установка необходимых пакетов и библиотек
  config.vm.provision "shell", inline: <<-SHELL
    # Обновляем пакеты
    apt-get update

    # Устанавливаем Python 3, pip и libpq-dev
    apt-get install -y python3 python3-pip libpq-dev

    # Устанавливаем библиотеки psycopg2 и Django
    pip3 install psycopg2-binary Django
  SHELL
end